Repository fack2/ptfb-griffinot, pull requests merged in 2019-10, with the labels that each got.

#52 Delete .eslintrc.js
  .eslintrc.js
  .eslintrc.json
Labels: awaiting-review

#50 created main files (file structure) #49
  src/CommonComponents/Header/index.js
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/Header/menu.js
  src/CommonComponents/Level/index.js
  src/CommonComponents/Level/index.style.js
  src/CommonComponents/NextPrevButton/index.js
  src/CommonComponents/NextPrevButton/index.style.js
  src/CommonComponents/Popup/index.js
  src/CommonComponents/Popup/index.style.js
  src/CommonComponents/Question/index.js
  src/CommonComponents/Question/index.style.js
  src/CommonComponents/Resource/index.js
  src/CommonComponents/Resource/index.style.js
  src/Data/data.json
  src/Layout/AboutUs/index.js
  src/Layout/AboutUs/index.style.js
  src/Layout/Blogs/index.js
  src/Layout/Blogs/index.style.js
  src/Layout/Books/index.js
  src/Layout/Books/index.style.js
  src/Layout/LandingPage/index.js
  src/Layout/LandingPage/index.style.js
  src/Layout/Levels/index.js
  src/Layout/Levels/index.style.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionB.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
  src/Layout/Questionnaire/SectionD2.js
  src/Layout/Questionnaire/index.js
  src/Layout/Questionnaire/index.style.js
  src/Layout/Resources/index.js
  src/Layout/Resources/index.style.js
  src/Layout/Videos/index.js
  src/Layout/Videos/index.style.js
  src/Layout/schem/index.js
  src/Layout/schem/index.style.js
Labels: approved

#59 Common component/question
  src/App.js
  src/CommonComponents/Question/index.js
  src/CommonComponents/Question/index.style.js
  src/Data/data.js
  src/Data/data.json
Labels: approved

#56 Common components/next prev button
  src/App.js
  src/CommonComponents/NextPrevButton/index.js
  src/CommonComponents/NextPrevButton/index.style.js
  src/assets/nextButton.png
  src/assets/prevButton.png
Labels: awaiting-review

#58 Layout/schema
  src/App.js
  src/Layout/Schema/index.js
  src/Layout/Schema/index.style.js
  src/Layout/schem/index.js
  src/Layout/schem/index.style.js
  src/assets/FMS-schema.jpg
  src/assets/right-arrow.png
Labels: approved

#62 Change the style to flex-box #27
  src/CommonComponents/Header/index.style.js
  src/Layout/LandingPage/index.style.js
Labels: approved

#60 Layout/about us
  src/App.js
  src/Layout/AboutUs/index.js
  src/Layout/AboutUs/index.style.js
  src/assets/KimG.png
Labels: approved

#63 change the container style to flex-box #32
  src/Layout/Schema/index.js
  src/Layout/Schema/index.style.js
Labels: approved

#65 Layout/menu
  src/App.js
  src/Layout/Menu/index.js
  src/Layout/Menu/index.style.js
  src/assets/aboutus.png
  src/assets/contactus.png
  src/assets/home.png
  src/assets/levels.png
  src/assets/resources.png
Labels: approved

#68 Common-component/linked-menu
  src/App.js
  src/CommonComponents/Header/index.js
Labels: approved

#69 Questionnaire data
  src/Data/data.js
  src/Data/questionnareData.js
Labels: approved

#66 Common components/prev next button
  src/CommonComponents/NextPrevButton/index.js
  src/CommonComponents/NextPrevButton/index.style.js
Labels: awaiting-review

#74 Layouts/about us
  public/index.html
  public/logo.ico
  src/Layout/AboutUs/index.js
  src/Layout/AboutUs/index.style.js
  src/Layout/Menu/index.js
  src/Layout/Schema/index.style.js
  src/assets/logo-aboutus.svg
Labels: approved

#64 create level common-component and styled it relate #43
  src/CommonComponents/Level/index.js
  src/CommonComponents/Level/index.style.js
Labels: request-change

#75 Common component/resource
  src/Data/resourceDate.js
  src/assets/IntroductoryVideos.jpg
  src/assets/PencilGraspTips.jpg
  src/assets/PencilGripReviews.jpg
  src/assets/SensoryEquipment.jpg
  src/assets/SensoryIntroduction.jpg
  src/assets/SensoryProcessingTraining.jpg
  src/assets/SensoryTopics.jpg
Labels: approved

#76 added a level page and style it relate #44
  src/App.js
  src/CommonComponents/Level/index.js
  src/CommonComponents/Level/index.style.js
  src/Data/levelData.js
  src/Layout/Levels/index.js
  src/Layout/Levels/index.style.js
Labels: approved

#67 Media queries
  src/Layout/LandingPage/index.style.js
  src/index.css
Labels: awaiting-review

#78 Common component/prev/next
  src/CommonComponents/NextButton/index.js
  src/CommonComponents/NextButton/index.style.js
  src/CommonComponents/PrevButton/index.js
  src/CommonComponents/PrevButton/index.style.js
Labels: awaiting-review

#80 Layout/schema popup
  package.json
  src/CommonComponents/PopupPage/index.js
  src/CommonComponents/PopupPage/index.style.js
  src/Layout/LandingPage/index.style.js
  src/Layout/Schema/index.js
  src/Layout/Schema/index.style.js
  src/assets/popup-logo.png
Labels: approved

#81 Common component/resource component
  src/App.js
  src/CommonComponents/NextButton/index.js
  src/CommonComponents/NextButton/index.style.js
  src/CommonComponents/PrevButton/index.js
  src/CommonComponents/PrevButton/index.style.js
  src/CommonComponents/Resource/index.js
  src/CommonComponents/Resource/index.style.js
  src/Data/resourceDate.js
  src/Layout/Resources/index.js
  src/Layout/Resources/index.style.js
  src/assets/book.png
Labels: Done

#79 Layout/option
  src/App.js
  src/CommonComponents/NextButton/index.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Questionnaire/index.style.js
Labels: awaiting-review

#82 Layout/Questionnaire section A #34
  src/App.js
  src/CommonComponents/NextButton/index.style.js
  src/CommonComponents/NextPrevButton/index.style.js
  src/CommonComponents/Question/index.js
  src/CommonComponents/Question/index.style.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/index.style.js
  src/index.css
Labels: awaiting-review

#86 Book Data
  src/Data/bookData.js
  src/assets/book1.jpeg
  src/assets/book2.jpg
Labels: awaiting-review

#84 Common component/blog
  src/CommonComponents/Blogs/index.js
  src/CommonComponents/Blogs/index.style.js
  src/assets/blog.png
  src/assets/blogger.png
Labels: awaiting-review

#88 edit the Resources page and use the map methode on it
  src/CommonComponents/Resource/index.js
  src/Layout/Resources/index.js
Labels: awaiting-review

#90 Layout/Questionnaire Section C
  src/App.js
  src/CommonComponents/NextPrevButton/index.js
  src/CommonComponents/NextPrevButton/index.style.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionB.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/index.style.js
Labels: Done

#91 Layout/questionnaire d1
  src/App.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
Labels: awaiting-review

#92 Layout/questionnaire d2 #38
  src/App.js
  src/Layout/Questionnaire/SectionD2.js
Labels: awaiting-review

#89 Layout/pop up
  src/CommonComponents/PopupPage/index.js
  src/CommonComponents/PopupPage/index.style.js
  src/Layout/Schema/index.js
  src/Layout/Schema/index.style.js
Labels: awaiting-review

#98 Refactor/next prev btn
  package.json
  src/CommonComponents/NextButton/index.js
  src/CommonComponents/NextButton/index.style.js
  src/CommonComponents/NextPrevButton/index.js
  src/CommonComponents/NextPrevButton/index.style.js
  src/CommonComponents/PrevButton/index.js
  src/CommonComponents/PrevButton/index.style.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionD2.js
Labels: approved

#97 deleted a heder in menu page
  src/App.js
Labels: approved

#101 Layout/menu
  src/CommonComponents/Header/index.js
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/Header/menu.js
  src/Layout/Menu/index.js
  src/Layout/Menu/index.style.js
  src/assets/close.png
Labels: awaiting-review

#99 Layout/book page
  src/App.js
  src/CommonComponents/Resource/index.js
  src/CommonComponents/Resource/index.style.js
  src/Data/bookData.js
  src/Layout/Books/index.js
  src/Layout/Books/index.style.js
  src/Layout/Resources/index.js
  src/assets/b1.png
  src/assets/b2.png
  src/assets/book-logo.png
  src/assets/book1.jpeg
  src/assets/book2.jpg
Labels: Done, approved

#105 fixed style of image in landing page
  src/Layout/LandingPage/index.style.js
Labels: awaiting-review

#111 Levels/responsive
  src/CommonComponents/Level/index.style.js
  src/Layout/Levels/index.style.js
Labels: awaiting-review

#104 Layout/Questionnaire
  src/App.js
  src/CommonComponents/NextButton/index.js
  src/CommonComponents/NextPrevButton/index.js
  src/CommonComponents/PopupPage/index.js
  src/CommonComponents/PrevButton/index.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Questionnaire/QuestionnaireData.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionB.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
  src/Layout/Questionnaire/SectionD2.js
  src/Layout/Questionnaire/index.js
  src/Layout/Questionnaire/index.style.js
  src/Layout/Schema/index.js
  src/index.css
Labels: approved

#116 Layout/questionnaire sections conditionl rendering
  src/CommonComponents/NextButton/index.js
  src/Layout/Questionnaire/SectionA.js
Labels: approved

#114 Commmon compoent/level pop up
  src/App.js
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/LevelPop/index.js
  src/CommonComponents/LevelPop/index.style.js
  src/CommonComponents/PopupPage/index.style.js
  src/Layout/Questionnaire/QuestionnaireData.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionB.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
  src/Layout/Questionnaire/SectionD2.js
  src/Layout/Questionnaire/index.js
  src/Layout/Questionnaire/index.style.js
Labels: awaiting-review

#115 Responsive/resources page
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/Resource/index.style.js
  src/Data/bookData.js
  src/Layout/Books/index.js
  src/Layout/Books/index.style.js
  src/Layout/Questionnaire/index.style.js
  src/Layout/Resources/index.style.js
Labels: in-progress

#124 Responsive/resources page
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/Resource/index.style.js
  src/Layout/Books/index.style.js
Labels: awaiting-review

#123 Landing page/responsive
  src/Layout/LandingPage/index.style.js
Labels: awaiting-review

#126 Schema/responsive
  src/CommonComponents/PopupPage/index.js
  src/CommonComponents/PopupPage/index.style.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Schema/index.style.js
Labels: awaiting-review

#133 Responsive/questionaire
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/Resource/index.style.js
  src/Layout/Books/index.style.js
  src/Layout/LandingPage/index.style.js
  src/Layout/Questionnaire/index.style.js
Labels: awaiting-review

#149 Page/not found
  public/index.html
  src/App.js
  src/CommonComponents/Header/index.js
  src/Layout/NotPageFound/index.js
  src/Layout/NotPageFound/index.style.js
  src/assets/NotFound.png
Labels: awaiting-review

#161 Resp/basic syle
  public/index.html
  src/index.css
Labels: awaiting-review

#163 Resp/landing page
  src/Layout/LandingPage/index.style.js
  src/index.css
Labels: approved

#167 Resp/schema
  src/Layout/LandingPage/index.style.js
  src/Layout/Schema/index.js
  src/Layout/Schema/index.style.js
Labels: awaiting-review

#152 Responsive-v2/Books #159
  public/index.html
  src/CommonComponents/Book/index.js
  src/CommonComponents/Book/index.style.js
  src/Data/bookData.js
  src/Layout/Books/index.js
  src/Layout/Books/index.style.js
  src/index.css
Labels: Done

#128 Leyout/sensory topics
  src/App.js
  src/Data/SensoryTopicsData.js
  src/Layout/ResourcesCategories/SensoryTopics.js
Labels: awaiting-review

#130 Layout/sensory equiment
  src/App.js
  src/Data/SensoryEquimentData.js
  src/Layout/ResourcesCategories/SensoryEquiment.js
Labels: awaiting-review

#131 Layout/fine motor
  src/App.js
  src/Data/FineMotorData.js
  src/Layout/ResourcesCategories/FineMotor.js
Labels: awaiting-review

#132 Layout/pencil grip
  src/App.js
  src/Data/PencilGripData.js
  src/Layout/ResourcesCategories/PencilGrip.js
Labels: awaiting-review

#176 Resp/pop up
  src/CommonComponents/PopupPage/index.js
  src/CommonComponents/PopupPage/index.style.js
  src/Layout/LandingPage/index.style.js
  src/Layout/Schema/index.js
  src/Layout/Schema/index.style.js
Labels: awaiting-review

#153 Responsive-v2/Resources #158
  src/CommonComponents/Header/index.js
  src/CommonComponents/Header/index.style.js
  src/CommonComponents/Resource/index.js
  src/CommonComponents/Resource/index.style.js
  src/Layout/Resources/index.js
  src/Layout/Resources/index.style.js
  src/index.css
Labels: awaiting-review

#177 Respnsive v2/questionnaire pages
  src/App.js
  src/CommonComponents/Header/index.style.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
  src/Layout/Questionnaire/SectionD2.js
  src/Layout/Questionnaire/index.js
  src/Layout/Questionnaire/index.style.js
  src/index.css
Labels: in-progress

#185 responsive menu
  src/Layout/Menu/index.js
  src/Layout/Menu/index.style.js
Labels: awaiting-review

#154 Responsive v2/videos #156
  src/Data/videoData.js
  src/Layout/Videos/index.js
  src/Layout/Videos/index.style.js
  src/assets/video-logo.png
  src/assets/video-logo.svg
Labels: Done

#191 Made header responsive for moew than one device
  src/CommonComponents/Header/index.style.js
Labels: Done

#174 changed the style of next and prev button make it more responsive
  src/CommonComponents/NextButton/index.js
  src/CommonComponents/NextButton/index.style.js
  src/CommonComponents/PrevButton/index.js
  src/CommonComponents/PrevButton/index.style.js
  src/Layout/Questionnaire/Option3.js
  src/Layout/Questionnaire/SectionB.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
  src/Layout/Questionnaire/SectionD2.js
  src/Layout/Questionnaire/index.style.js
  src/Layout/Resources/index.js
  src/Layout/ResourcesCategories/FineMotor.js
  src/Layout/ResourcesCategories/PencilGrip.js
  src/Layout/ResourcesCategories/SensoryEquiment.js
  src/Layout/ResourcesCategories/SensoryIntroduction.js
  src/Layout/ResourcesCategories/SensoryTopics.js
  src/Layout/ResourcesCategories/SensoryTraining.js
Labels: in-progress

#194 Refactor/question card
  src/Layout/Questionnaire/SectionA.js
  src/Layout/Questionnaire/SectionB.js
  src/Layout/Questionnaire/SectionC.js
  src/Layout/Questionnaire/SectionD1.js
  src/Layout/Questionnaire/SectionD2.js
  src/Layout/Questionnaire/index.js
Labels: awaiting-review
